# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "devel"
  name = "github.com/go-yaml/yaml"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "3d4380f53a34dcdc95f0c1db702615992b38d9a4"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/ksonnet/ksonnet-lib"
  source = "github.com/bryanl/ksonnet-lib"
  branch = "bug-nested-map-string"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.0"

[[constraint]]
  name = "github.com/ksonnet/ksonnet"
  revision = "82e578960fdc026bbe7a79070d707a506f941ad4"

[[constraint]]
  name = "github.com/PuerkitoBio/purell"
  revision = "b938d81255b5473c57635324295cb0fe398c7a58"

[[override]]
  name = "github.com/google/go-jsonnet"
  revision = "e8f6d25f61d163deee16a78b545f4aaa0f295c01"
